<?php

namespace Database\Seeders\Modules\GSO;

use Database\Seeders\Concerns\SeedsModulePermissions;
use Illuminate\Database\Seeder;

class GsoPermissionSeeder extends Seeder
{
    use SeedsModulePermissions;

    public function run(): void
    {
        $this->seedGroupedPermissions('GSO', [
            'GSO / Tasks' => [
                'tasks.view',
                'tasks.view_all',
                'tasks.claim',
                'tasks.comment',
                'tasks.update_status',
                'tasks.reassign',
            ],
            'GSO / AIR' => [
                'air.view',
                'air.create',
                'air.update',
                'air.inspect',
                'air.finalize_inspection',
                'air.reopen_inspection',
                'air.manage_items',
                'air.manage_files',
                'air.promote_inventory',
                'air.archive',
                'air.restore',
                'air.print',
                'air.upload_signed_pdf',
            ],
            'GSO / RIS' => [
                'ris.view',
                'ris.create',
                'ris.update',
                'ris.submit',
                'ris.approve',
                'ris.reject',
                'ris.reopen',
                'ris.revert',
                'ris.archive',
                'ris.restore',
                'ris.manage_items',
                'ris.generate_from_air',
                'ris.print',
                'ris.upload_signed_pdf',
            ],
            'GSO / PAR' => [
                'par.view',
                'par.create',
                'par.update',
                'par.submit',
                'par.finalize',
                'par.reopen',
                'par.archive',
                'par.restore',
                'par.manage_items',
                'par.print',
                'par.upload_signed_pdf',
            ],
            'GSO / ICS' => [
                'ics.view',
                'ics.create',
                'ics.update',
                'ics.submit',
                'ics.finalize',
                'ics.reopen',
                'ics.archive',
                'ics.restore',
                'ics.manage_items',
                'ics.print',
                'ics.upload_signed_pdf',
            ],
            'GSO / PTR' => [
                'ptr.view',
                'ptr.create',
                'ptr.update',
                'ptr.submit',
                'ptr.finalize',
                'ptr.reopen',
                'ptr.archive',
                'ptr.restore',
                'ptr.manage_items',
                'ptr.print',
                'ptr.upload_signed_pdf',
            ],
            'GSO / ITR' => [
                'itr.view',
                'itr.create',
                'itr.update',
                'itr.submit',
                'itr.finalize',
                'itr.reopen',
                'itr.archive',
                'itr.restore',
                'itr.manage_items',
                'itr.print',
                'itr.upload_signed_pdf',
            ],
            'GSO / WMR' => [
                'wmr.view',
                'wmr.create',
                'wmr.update',
                'wmr.submit',
                'wmr.approve',
                'wmr.finalize',
                'wmr.reopen',
                'wmr.archive',
                'wmr.restore',
                'wmr.manage_items',
                'wmr.print',
                'wmr.upload_signed_pdf',
            ],
            'GSO / Inventory' => [
                'items.view',
                'items.create',
                'items.update',
                'items.archive',
                'items.restore',
                'inventory_items.view',
                'inventory_items.create',
                'inventory_items.update',
                'inventory_items.archive',
                'inventory_items.restore',
                'inventory_items.manage_files',
                'inventory_items.manage_events',
                'inventory_items.import_from_inspection',
                'stocks.view',
                'stocks.adjust',
                'stocks.view_ledger',
                'inspections.view',
                'inspections.create',
                'inspections.update',
                'inspections.archive',
                'inspections.restore',
                'inspections.manage_photos',
            ],
            'GSO / Reference Data' => [
                'asset_types.view',
                'asset_types.create',
                'asset_types.update',
                'asset_types.archive',
                'asset_types.restore',
                'asset_categories.view',
                'asset_categories.create',
                'asset_categories.update',
                'asset_categories.archive',
                'asset_categories.restore',
                'departments.view',
                'departments.create',
                'departments.update',
                'departments.archive',
                'departments.restore',
                'fund_clusters.view',
                'fund_clusters.create',
                'fund_clusters.update',
                'fund_clusters.archive',
                'fund_clusters.restore',
                'fund_sources.view',
                'fund_sources.create',
                'fund_sources.update',
                'fund_sources.archive',
                'fund_sources.restore',
                'accountable_persons.view',
                'accountable_persons.create',
                'accountable_persons.update',
                'accountable_persons.archive',
                'accountable_persons.restore',
            ],
            'GSO / Reports' => [
                'reports.rpci.view',
                'reports.rpcppe.view',
                'reports.rpcsp.view',
                'reports.regspi.view',
                'reports.rspi.view',
                'reports.rrsp.view',
                'reports.ssmi.view',
                'reports.property_cards.view',
                'reports.stickers.view',
                'reports.stock_cards.view',
            ],
            'GSO / Module Access' => [
                'access.users.view',
                'access.users.manage',
                'access.roles.view',
                'access.roles.manage',
                'access.permissions.view',
                'access.permissions.manage',
                'audit_logs.view',
                'audit_logs.print',
                'audit_logs.restore_data',
            ],
            'GSO / Theme' => [
                'theme.update_colors',
            ],
        ]);

        $this->command?->info('GSO normalized permissions seeded successfully.');
    }
}
