<?php

$config = [
    'printables' => [
        'gso_air' => [
            'module' => 'GSO',
            'default_paper' => 'a4-portrait',
            'allowed_papers' => [
                'a4-portrait',
                'letter-portrait',
                'legal-portrait',
            ],
            'profiles' => [
                'a4-portrait' => [
                    'pages_view' => 'gso::air.print.paper.a4-portrait.pages',
                    'styles_view' => 'gso::air.print.paper.a4-portrait.styles',
                    'pdf_styles_view' => 'gso::air.print.paper.a4-portrait.pdf-styles',
                    'rows_per_page' => 19,
                    'grid_rows' => 19,
                    'last_page_grid_rows' => 19,
                    'description_chars_per_line' => 73,
                    'header_image_web' => 'headers/Picture1.png',
                    'footer_image_web' => 'headers/Picture2.png',
                    'header_image_pdf' => 'headers/Picture1.png',
                    'footer_image_pdf' => 'headers/Picture2.png',

                    'pdf_preview_fragment' => 'toolbar=0&navpanes=0&scrollbar=0&zoom=98',

                ],
                'letter-portrait' => [
                    'pages_view' => 'gso::air.print.paper.letter-portrait.pages',
                    'styles_view' => 'gso::air.print.paper.letter-portrait.styles',
                    'pdf_styles_view' => 'gso::air.print.paper.letter-portrait.pdf-styles',
                    'rows_per_page' => 16,
                    'grid_rows' => 16,
                    'last_page_grid_rows' => 16,
                    'description_chars_per_line' => 40,

                    'pdf_preview_fragment' => 'toolbar=0&navpanes=0&scrollbar=0&zoom=90',
                ],
                'legal-portrait' => [
                    'pages_view' => 'gso::air.print.paper.legal-portrait.pages',
                    'styles_view' => 'gso::air.print.paper.legal-portrait.styles',
                    'pdf_styles_view' => 'gso::air.print.paper.legal-portrait.pdf-styles',
                    'rows_per_page' => 23,
                    'grid_rows' => 23,
                    'last_page_grid_rows' => 23,
                    'description_chars_per_line' => 72,
                ],
            ],
        ],
        'gso_ris' => [
            'module' => 'GSO',
            'default_paper' => 'a4-portrait',
            'allowed_papers' => [
                'a4-portrait',
                'letter-portrait',
                'legal-portrait',
            ],
            'profiles' => [
                'a4-portrait' => [
                    'pages_view' => 'gso::ris.print.paper.a4-portrait.pages',
                    'styles_view' => 'gso::ris.print.paper.a4-portrait.styles',
                    'pdf_styles_view' => 'gso::ris.print.paper.a4-portrait.pdf-styles',
                    'rows_per_page' => 60,
                    'grid_rows' => 60,
                    'last_page_grid_rows' => 33,
                    'description_chars_per_line' => 50,
                    'item_column_widths' => [
                        'stock_no' => '15%',
                        'unit' => '7%',
                        'description' => '50%',
                        'qty_requested' => '8%',
                        'qty_issued' => '8%',
                        'remarks' => '12%',
                    ],
                ],
                'letter-portrait' => [
                    'pages_view' => 'gso::ris.print.paper.letter-portrait.pages',
                    'styles_view' => 'gso::ris.print.paper.letter-portrait.styles',
                    'pdf_styles_view' => 'gso::ris.print.paper.letter-portrait.pdf-styles',
                    'rows_per_page' => 68,
                    'grid_rows' => 68,
                    'last_page_grid_rows' => 29,
                    'description_chars_per_line' => 40,
                ],
                'legal-portrait' => [
                    'pages_view' => 'gso::ris.print.paper.legal-portrait.pages',
                    'styles_view' => 'gso::ris.print.paper.legal-portrait.styles',
                    'pdf_styles_view' => 'gso::ris.print.paper.legal-portrait.pdf-styles',
                    'rows_per_page' => 76,
                    'grid_rows' => 76,
                    'last_page_grid_rows' => 37,
                    'description_chars_per_line' => 40,
                ],
            ],
        ],
        'gso_rpci' => [
            'module' => 'GSO',
            'default_paper' => 'a4-landscape',
            'allowed_papers' => [
                'a4-landscape',
                'letter-landscape',
                'legal-landscape',
            ],
            'profiles' => [
                'a4-landscape' => [
                    'pages_view' => 'gso::reports.rpci.print.paper.a4-landscape.pages',
                    'styles_view' => 'gso::reports.rpci.print.paper.a4-landscape.styles',
                    'pdf_styles_view' => 'gso::reports.rpci.print.paper.a4-landscape.pdf-styles',
                    'chrome_pdf_styles_view' => 'gso::reports.rpci.print.paper.a4-landscape.pdf-styles-chrome',
                    'dompdf_pdf_styles_view' => 'gso::reports.rpci.print.paper.a4-landscape.pdf-styles-dompdf',
                    'chrome_pdf_pages_view' => 'gso::reports.rpci.print.paper.a4-landscape.pdf-pages-chrome',
                    'dompdf_pdf_pages_view' => 'gso::reports.rpci.print.paper.a4-landscape.pdf-pages-dompdf',
                    'rows_per_page' => 14,
                    'grid_rows' => 14,
                    'last_page_grid_rows' => 14,
                    'description_chars_per_line' => 44,
                    'header_image_web' => 'headers/a4_landscape_header_dark_3508x300.png',
                    'footer_image_web' => 'headers/a4_landscape_footer_dark_3508x250.png',
                    'header_image_pdf' => 'headers/a4_landscape_header_dark_3508x300.png',
                    'footer_image_pdf' => 'headers/a4_landscape_footer_dark_3508x250.png',
                ],
                'letter-landscape' => [
                    'pages_view' => 'gso::reports.rpci.print.paper.letter-landscape.pages',
                    'styles_view' => 'gso::reports.rpci.print.paper.letter-landscape.styles',
                    'pdf_styles_view' => 'gso::reports.rpci.print.paper.letter-landscape.pdf-styles',
                    'chrome_pdf_styles_view' => 'gso::reports.rpci.print.paper.letter-landscape.pdf-styles-chrome',
                    'dompdf_pdf_styles_view' => 'gso::reports.rpci.print.paper.letter-landscape.pdf-styles-dompdf',
                    'chrome_pdf_pages_view' => 'gso::reports.rpci.print.paper.letter-landscape.pdf-pages-chrome',
                    'dompdf_pdf_pages_view' => 'gso::reports.rpci.print.paper.letter-landscape.pdf-pages-dompdf',
                    'rows_per_page' => 14,
                    'grid_rows' => 14,
                    'last_page_grid_rows' => 16,
                    'description_chars_per_line' => 50,
                    'header_image_web' => 'headers/letter_landscape_header_3300x300.png',
                    'footer_image_web' => 'headers/letter_landscape_footer_3300x250.png',
                    'header_image_pdf' => 'headers/letter_landscape_header_3300x300.png',
                    'footer_image_pdf' => 'headers/letter_landscape_footer_3300x250.png',
                ],
                'legal-landscape' => [
                    'pages_view' => 'gso::reports.rpci.print.paper.legal-landscape.pages',
                    'styles_view' => 'gso::reports.rpci.print.paper.legal-landscape.styles',
                    'pdf_styles_view' => 'gso::reports.rpci.print.paper.legal-landscape.pdf-styles',
                    'chrome_pdf_styles_view' => 'gso::reports.rpci.print.paper.legal-landscape.pdf-styles-chrome',
                    'dompdf_pdf_styles_view' => 'gso::reports.rpci.print.paper.legal-landscape.pdf-styles-dompdf',
                    'chrome_pdf_pages_view' => 'gso::reports.rpci.print.paper.legal-landscape.pdf-pages-chrome',
                    'dompdf_pdf_pages_view' => 'gso::reports.rpci.print.paper.legal-landscape.pdf-pages-dompdf',
                    'rows_per_page' => 16,
                    'grid_rows' => 15,
                    'last_page_grid_rows' => 16,
                    'description_chars_per_line' => 60,
                    'header_image_web' => 'headers/longbond_landscape_header_3900x300.png',
                    'footer_image_web' => 'headers/longbond_landscape_footer_3900x250.png',
                    'header_image_pdf' => 'headers/longbond_landscape_header_3900x300.png',
                    'footer_image_pdf' => 'headers/longbond_landscape_footer_3900x250.png',
                ],
            ],
        ],
        'gso_rpcppe' => [
            'module' => 'GSO',
            'default_paper' => 'a4-landscape',
            'allowed_papers' => [
                'a4-landscape',
                'letter-landscape',
                'legal-landscape',
            ],
            'profiles' => [
                'a4-landscape' => [
                    'pages_view' => 'gso::reports.rpcppe.print.paper.a4-landscape.pages',
                    'styles_view' => 'gso::reports.rpcppe.print.paper.a4-landscape.styles',
                    'pdf_styles_view' => 'gso::reports.rpcppe.print.paper.a4-landscape.pdf-styles',
                    'rows_per_page' => 13,
                    'grid_rows' => 13,
                    'last_page_grid_rows' => 6,
                    'description_chars_per_line' => 44,
                    'header_image_web' => 'headers/a4_landscape_header_dark_3508x300.png',
                    'footer_image_web' => 'headers/a4_landscape_footer_dark_3508x250.png',
                    'header_image_pdf' => 'headers/a4_landscape_header_dark_3508x300.png',
                    'footer_image_pdf' => 'headers/a4_landscape_footer_dark_3508x250.png',
                ],
                'letter-landscape' => [
                    'pages_view' => 'gso::reports.rpcppe.print.paper.letter-landscape.pages',
                    'styles_view' => 'gso::reports.rpcppe.print.paper.letter-landscape.styles',
                    'pdf_styles_view' => 'gso::reports.rpcppe.print.paper.letter-landscape.pdf-styles',
                    'rows_per_page' => 13,
                    'grid_rows' => 13,
                    'last_page_grid_rows' => 6,
                    'description_chars_per_line' => 50,
                    'header_image_web' => 'headers/letter_landscape_header_3300x300.png',
                    'footer_image_web' => 'headers/letter_landscape_footer_3300x250.png',
                    'header_image_pdf' => 'headers/letter_landscape_header_3300x300.png',
                    'footer_image_pdf' => 'headers/letter_landscape_footer_3300x250.png',
                ],
                'legal-landscape' => [
                    'pages_view' => 'gso::reports.rpcppe.print.paper.legal-landscape.pages',
                    'styles_view' => 'gso::reports.rpcppe.print.paper.legal-landscape.styles',
                    'pdf_styles_view' => 'gso::reports.rpcppe.print.paper.legal-landscape.pdf-styles',
                    'rows_per_page' => 14,
                    'grid_rows' => 14,
                    'last_page_grid_rows' => 7,
                    'description_chars_per_line' => 58,
                    'header_image_web' => 'headers/longbond_landscape_header_3900x300.png',
                    'footer_image_web' => 'headers/longbond_landscape_footer_3900x250.png',
                    'header_image_pdf' => 'headers/longbond_landscape_header_3900x300.png',
                    'footer_image_pdf' => 'headers/longbond_landscape_footer_3900x250.png',
                ],
            ],
        ],
        'gso_regspi' => [
            'module' => 'GSO',
            'default_paper' => 'a4-landscape',
            'allowed_papers' => [
                'a4-landscape',
                'letter-landscape',
                'legal-landscape',
            ],
            'profiles' => [
                'a4-landscape' => [
                    'pages_view' => 'gso::reports.regspi.print.paper.a4-landscape.pages',
                    'styles_view' => 'gso::reports.regspi.print.paper.a4-landscape.styles',
                    'pdf_styles_view' => 'gso::reports.regspi.print.paper.a4-landscape.pdf-styles',
                    'rows_per_page' => 14,
                    'grid_rows' => 14,
                    'last_page_grid_rows' => 8,
                    'description_chars_per_line' => 52,
                    'header_image_web' => 'headers/a4_landscape_header_dark_3508x300.png',
                    'footer_image_web' => 'headers/a4_landscape_footer_dark_3508x250.png',
                    'header_image_pdf' => 'headers/a4_landscape_header_dark_3508x300.png',
                    'footer_image_pdf' => 'headers/a4_landscape_footer_dark_3508x250.png',
                ],
                'letter-landscape' => [
                    'pages_view' => 'gso::reports.regspi.print.paper.letter-landscape.pages',
                    'styles_view' => 'gso::reports.regspi.print.paper.letter-landscape.styles',
                    'pdf_styles_view' => 'gso::reports.regspi.print.paper.letter-landscape.pdf-styles',
                    'rows_per_page' => 14,
                    'grid_rows' => 14,
                    'last_page_grid_rows' => 8,
                    'description_chars_per_line' => 58,
                    'header_image_web' => 'headers/letter_landscape_header_3300x300.png',
                    'footer_image_web' => 'headers/letter_landscape_footer_3300x250.png',
                    'header_image_pdf' => 'headers/letter_landscape_header_3300x300.png',
                    'footer_image_pdf' => 'headers/letter_landscape_footer_3300x250.png',
                ],
                'legal-landscape' => [
                    'pages_view' => 'gso::reports.regspi.print.paper.legal-landscape.pages',
                    'styles_view' => 'gso::reports.regspi.print.paper.legal-landscape.styles',
                    'pdf_styles_view' => 'gso::reports.regspi.print.paper.legal-landscape.pdf-styles',
                    'rows_per_page' => 16,
                    'grid_rows' => 16,
                    'last_page_grid_rows' => 10,
                    'description_chars_per_line' => 66,
                    'header_image_web' => 'headers/longbond_landscape_header_3900x300.png',
                    'footer_image_web' => 'headers/longbond_landscape_footer_3900x250.png',
                    'header_image_pdf' => 'headers/longbond_landscape_header_3900x300.png',
                    'footer_image_pdf' => 'headers/longbond_landscape_footer_3900x250.png',
                ],
            ],
        ],
        'gso_rspi' => [
            'module' => 'GSO',
            'default_paper' => 'a4-landscape',
            'allowed_papers' => [
                'a4-landscape',
                'letter-landscape',
                'legal-landscape',
            ],
            'profiles' => [
                'a4-landscape' => [
                    'pages_view' => 'gso::reports.rspi.print.paper.a4-landscape.pages',
                    'styles_view' => 'gso::reports.rspi.print.paper.a4-landscape.styles',
                    'pdf_styles_view' => 'gso::reports.rspi.print.paper.a4-landscape.pdf-styles',
                    'rows_per_page' => 15,
                    'grid_rows' => 15,
                    'last_page_grid_rows' => 8,
                    'description_chars_per_line' => 52,
                    'header_image_web' => 'headers/a4_landscape_header_dark_3508x300.png',
                    'footer_image_web' => 'headers/a4_landscape_footer_dark_3508x250.png',
                    'header_image_pdf' => 'headers/a4_landscape_header_dark_3508x300.png',
                    'footer_image_pdf' => 'headers/a4_landscape_footer_dark_3508x250.png',
                ],
                'letter-landscape' => [
                    'pages_view' => 'gso::reports.rspi.print.paper.letter-landscape.pages',
                    'styles_view' => 'gso::reports.rspi.print.paper.letter-landscape.styles',
                    'pdf_styles_view' => 'gso::reports.rspi.print.paper.letter-landscape.pdf-styles',
                    'rows_per_page' => 15,
                    'grid_rows' => 15,
                    'last_page_grid_rows' => 8,
                    'description_chars_per_line' => 58,
                    'header_image_web' => 'headers/letter_landscape_header_3300x300.png',
                    'footer_image_web' => 'headers/letter_landscape_footer_3300x250.png',
                    'header_image_pdf' => 'headers/letter_landscape_header_3300x300.png',
                    'footer_image_pdf' => 'headers/letter_landscape_footer_3300x250.png',
                ],
                'legal-landscape' => [
                    'pages_view' => 'gso::reports.rspi.print.paper.legal-landscape.pages',
                    'styles_view' => 'gso::reports.rspi.print.paper.legal-landscape.styles',
                    'pdf_styles_view' => 'gso::reports.rspi.print.paper.legal-landscape.pdf-styles',
                    'rows_per_page' => 17,
                    'grid_rows' => 17,
                    'last_page_grid_rows' => 10,
                    'description_chars_per_line' => 66,
                    'header_image_web' => 'headers/longbond_landscape_header_3900x300.png',
                    'footer_image_web' => 'headers/longbond_landscape_footer_3900x250.png',
                    'header_image_pdf' => 'headers/longbond_landscape_header_3900x300.png',
                    'footer_image_pdf' => 'headers/longbond_landscape_footer_3900x250.png',
                ],
            ],
        ],
        'gso_rrsp' => [
            'module' => 'GSO',
            'default_paper' => 'a4-landscape',
            'allowed_papers' => [
                'a4-landscape',
                'letter-landscape',
                'legal-landscape',
            ],
            'profiles' => [
                'a4-landscape' => [
                    'pages_view' => 'gso::reports.rrsp.print.paper.a4-landscape.pages',
                    'styles_view' => 'gso::reports.rrsp.print.paper.a4-landscape.styles',
                    'pdf_styles_view' => 'gso::reports.rrsp.print.paper.a4-landscape.pdf-styles',
                    'rows_per_page' => 15,
                    'grid_rows' => 15,
                    'last_page_grid_rows' => 8,
                    'description_chars_per_line' => 52,
                    'header_image_web' => 'headers/a4_landscape_header_dark_3508x300.png',
                    'footer_image_web' => 'headers/a4_landscape_footer_dark_3508x250.png',
                    'header_image_pdf' => 'headers/a4_landscape_header_dark_3508x300.png',
                    'footer_image_pdf' => 'headers/a4_landscape_footer_dark_3508x250.png',
                ],
                'letter-landscape' => [
                    'pages_view' => 'gso::reports.rrsp.print.paper.letter-landscape.pages',
                    'styles_view' => 'gso::reports.rrsp.print.paper.letter-landscape.styles',
                    'pdf_styles_view' => 'gso::reports.rrsp.print.paper.letter-landscape.pdf-styles',
                    'rows_per_page' => 15,
                    'grid_rows' => 15,
                    'last_page_grid_rows' => 8,
                    'description_chars_per_line' => 58,
                    'header_image_web' => 'headers/letter_landscape_header_3300x300.png',
                    'footer_image_web' => 'headers/letter_landscape_footer_3300x250.png',
                    'header_image_pdf' => 'headers/letter_landscape_header_3300x300.png',
                    'footer_image_pdf' => 'headers/letter_landscape_footer_3300x250.png',
                ],
                'legal-landscape' => [
                    'pages_view' => 'gso::reports.rrsp.print.paper.legal-landscape.pages',
                    'styles_view' => 'gso::reports.rrsp.print.paper.legal-landscape.styles',
                    'pdf_styles_view' => 'gso::reports.rrsp.print.paper.legal-landscape.pdf-styles',
                    'rows_per_page' => 17,
                    'grid_rows' => 17,
                    'last_page_grid_rows' => 10,
                    'description_chars_per_line' => 66,
                    'header_image_web' => 'headers/longbond_landscape_header_3900x300.png',
                    'footer_image_web' => 'headers/longbond_landscape_footer_3900x250.png',
                    'header_image_pdf' => 'headers/longbond_landscape_header_3900x300.png',
                    'footer_image_pdf' => 'headers/longbond_landscape_footer_3900x250.png',
                ],
            ],
        ],
        'gso_ssmi' => [
            'module' => 'GSO',
            'default_paper' => 'a4-landscape',
            'allowed_papers' => [
                'a4-landscape',
                'letter-landscape',
                'legal-landscape',
            ],
            'profiles' => [
                'a4-landscape' => [
                    'pages_view' => 'gso::reports.ssmi.print.paper.a4-landscape.pages',
                    'styles_view' => 'gso::reports.ssmi.print.paper.a4-landscape.styles',
                    'pdf_styles_view' => 'gso::reports.ssmi.print.paper.a4-landscape.pdf-styles',
                    'rows_per_page' => 15,
                    'grid_rows' => 15,
                    'last_page_grid_rows' => 8,
                    'description_chars_per_line' => 44,
                    'header_image_web' => 'headers/a4_landscape_header_dark_3508x300.png',
                    'footer_image_web' => 'headers/a4_landscape_footer_dark_3508x250.png',
                    'header_image_pdf' => 'headers/a4_landscape_header_dark_3508x300.png',
                    'footer_image_pdf' => 'headers/a4_landscape_footer_dark_3508x250.png',
                ],
                'letter-landscape' => [
                    'pages_view' => 'gso::reports.ssmi.print.paper.letter-landscape.pages',
                    'styles_view' => 'gso::reports.ssmi.print.paper.letter-landscape.styles',
                    'pdf_styles_view' => 'gso::reports.ssmi.print.paper.letter-landscape.pdf-styles',
                    'rows_per_page' => 15,
                    'grid_rows' => 15,
                    'last_page_grid_rows' => 8,
                    'description_chars_per_line' => 50,
                    'header_image_web' => 'headers/letter_landscape_header_3300x300.png',
                    'footer_image_web' => 'headers/letter_landscape_footer_3300x250.png',
                    'header_image_pdf' => 'headers/letter_landscape_header_3300x300.png',
                    'footer_image_pdf' => 'headers/letter_landscape_footer_3300x250.png',
                ],
                'legal-landscape' => [
                    'pages_view' => 'gso::reports.ssmi.print.paper.legal-landscape.pages',
                    'styles_view' => 'gso::reports.ssmi.print.paper.legal-landscape.styles',
                    'pdf_styles_view' => 'gso::reports.ssmi.print.paper.legal-landscape.pdf-styles',
                    'rows_per_page' => 17,
                    'grid_rows' => 17,
                    'last_page_grid_rows' => 10,
                    'description_chars_per_line' => 58,
                    'header_image_web' => 'headers/longbond_landscape_header_3900x300.png',
                    'footer_image_web' => 'headers/longbond_landscape_footer_3900x250.png',
                    'header_image_pdf' => 'headers/longbond_landscape_header_3900x300.png',
                    'footer_image_pdf' => 'headers/longbond_landscape_footer_3900x250.png',
                ],
            ],
        ],
        'gso_property_cards' => [
            'module' => 'GSO',
            'default_paper' => 'a4-landscape',
            'allowed_papers' => [
                'a4-landscape',
                'letter-landscape',
                'legal-landscape',
            ],
            'profiles' => [
                'a4-landscape' => [
                    'pages_view' => 'gso::reports.property-cards.print.paper.a4-landscape.pages',
                    'styles_view' => 'gso::reports.property-cards.print.paper.a4-landscape.styles',
                    'pdf_styles_view' => 'gso::reports.property-cards.print.paper.a4-landscape.pdf-styles',
                ],
                'letter-landscape' => [
                    'pages_view' => 'gso::reports.property-cards.print.paper.letter-landscape.pages',
                    'styles_view' => 'gso::reports.property-cards.print.paper.letter-landscape.styles',
                    'pdf_styles_view' => 'gso::reports.property-cards.print.paper.letter-landscape.pdf-styles',
                ],
                'legal-landscape' => [
                    'pages_view' => 'gso::reports.property-cards.print.paper.legal-landscape.pages',
                    'styles_view' => 'gso::reports.property-cards.print.paper.legal-landscape.styles',
                    'pdf_styles_view' => 'gso::reports.property-cards.print.paper.legal-landscape.pdf-styles',
                ],
            ],
        ],
        'gso_rpcsp' => [
            'module' => 'GSO',
            'default_paper' => 'a4-landscape',
            'allowed_papers' => [
                'a4-landscape',
                'letter-landscape',
                'legal-landscape',
            ],
            'profiles' => [
                'a4-landscape' => [
                    'pages_view' => 'gso::reports.rpcsp.print.paper.a4-landscape.pages',
                    'styles_view' => 'gso::reports.rpcsp.print.paper.a4-landscape.styles',
                    'pdf_styles_view' => 'gso::reports.rpcsp.print.paper.a4-landscape.pdf-styles',
                    'rows_per_page' => 13,
                    'grid_rows' => 13,
                    'last_page_grid_rows' => 6,
                    'description_chars_per_line' => 44,
                    'header_image_web' => 'headers/a4_landscape_header_dark_3508x300.png',
                    'footer_image_web' => 'headers/a4_landscape_footer_dark_3508x250.png',
                    'header_image_pdf' => 'headers/a4_landscape_header_dark_3508x300.png',
                    'footer_image_pdf' => 'headers/a4_landscape_footer_dark_3508x250.png',
                ],
                'letter-landscape' => [
                    'pages_view' => 'gso::reports.rpcsp.print.paper.letter-landscape.pages',
                    'styles_view' => 'gso::reports.rpcsp.print.paper.letter-landscape.styles',
                    'pdf_styles_view' => 'gso::reports.rpcsp.print.paper.letter-landscape.pdf-styles',
                    'rows_per_page' => 13,
                    'grid_rows' => 13,
                    'last_page_grid_rows' => 6,
                    'description_chars_per_line' => 50,
                    'header_image_web' => 'headers/letter_landscape_header_3300x300.png',
                    'footer_image_web' => 'headers/letter_landscape_footer_3300x250.png',
                    'header_image_pdf' => 'headers/letter_landscape_header_3300x300.png',
                    'footer_image_pdf' => 'headers/letter_landscape_footer_3300x250.png',
                ],
                'legal-landscape' => [
                    'pages_view' => 'gso::reports.rpcsp.print.paper.legal-landscape.pages',
                    'styles_view' => 'gso::reports.rpcsp.print.paper.legal-landscape.styles',
                    'pdf_styles_view' => 'gso::reports.rpcsp.print.paper.legal-landscape.pdf-styles',
                    'rows_per_page' => 14,
                    'grid_rows' => 14,
                    'last_page_grid_rows' => 7,
                    'description_chars_per_line' => 58,
                    'header_image_web' => 'headers/longbond_landscape_header_3900x300.png',
                    'footer_image_web' => 'headers/longbond_landscape_footer_3900x250.png',
                    'header_image_pdf' => 'headers/longbond_landscape_header_3900x300.png',
                    'footer_image_pdf' => 'headers/longbond_landscape_footer_3900x250.png',
                ],
            ],
        ],
        'gso_par' => [
            'module' => 'GSO',
            'default_paper' => 'a4-portrait',
            'allowed_papers' => [
                'a4-portrait',
                'letter-portrait',
                'legal-portrait',
            ],
            'profiles' => [
                'a4-portrait' => [
                    'pages_view' => 'gso::pars.print.paper.a4-portrait.pages',
                    'styles_view' => 'gso::pars.print.paper.a4-portrait.styles',
                    'pdf_styles_view' => 'gso::pars.print.paper.a4-portrait.pdf-styles',
                    'rows_per_page' => 26,
                    'grid_rows' => 26,
                    'last_page_grid_rows' => 26,
                    'description_chars_per_line' => 40,
                    'item_column_widths' => [
                        'qty' => '6%',
                        'unit' => '7%',
                        'description' => '32%',
                        'property_number' => '25%',
                        'date_acquired' => '15%',
                        'amount' => '15%',
                    ],
                    'header_image_web' => 'headers/Picture1.png',
                    'footer_image_web' => 'headers/Picture2.png',
                ],
                'letter-portrait' => [
                    'pages_view' => 'gso::pars.print.paper.letter-portrait.pages',
                    'styles_view' => 'gso::pars.print.paper.letter-portrait.styles',
                    'pdf_styles_view' => 'gso::pars.print.paper.letter-portrait.pdf-styles',
                    'rows_per_page' => 23,
                    'grid_rows' => 23,
                    'last_page_grid_rows' => 23,
                    'description_chars_per_line' => 38,
                    'header_image_web' => 'headers/Picture1.png',
                    'footer_image_web' => 'headers/Picture2.png',
                ],
                'legal-portrait' => [
                    'pages_view' => 'gso::pars.print.paper.legal-portrait.pages',
                    'styles_view' => 'gso::pars.print.paper.legal-portrait.styles',
                    'pdf_styles_view' => 'gso::pars.print.paper.legal-portrait.pdf-styles',
                    'rows_per_page' => 30,
                    'grid_rows' => 30,
                    'last_page_grid_rows' => 30,
                    'description_chars_per_line' => 42,
                    'header_image_web' => 'headers/Picture1.png',
                    'footer_image_web' => 'headers/Picture2.png',
                ],
            ],
        ],
        'gso_ptr' => [
            'module' => 'GSO',
            'default_paper' => 'a4-portrait',
            'allowed_papers' => [
                'a4-portrait',
                'letter-portrait',
                'legal-portrait',
            ],
            'profiles' => [
                'a4-portrait' => [
                    'pages_view' => 'gso::ptrs.print.paper.a4-portrait.pages',
                    'styles_view' => 'gso::ptrs.print.paper.a4-portrait.styles',
                    'pdf_styles_view' => 'gso::ptrs.print.paper.a4-portrait.pdf-styles',
                    'rows_per_page' => 20,
                    'grid_rows' => 12,
                    'last_page_grid_rows' => 20,
                    'description_chars_per_line' => 38,
                    'header_image_web' => 'headers/Picture1.png',
                    'footer_image_web' => 'headers/Picture2.png',
                    'header_image_pdf' => 'headers/Picture1.png',
                    'footer_image_pdf' => 'headers/Picture2.png',
                ],
                'letter-portrait' => [
                    'pages_view' => 'gso::ptrs.print.paper.letter-portrait.pages',
                    'styles_view' => 'gso::ptrs.print.paper.letter-portrait.styles',
                    'pdf_styles_view' => 'gso::ptrs.print.paper.letter-portrait.pdf-styles',
                    'rows_per_page' => 17,
                    'grid_rows' => 11,
                    'last_page_grid_rows' => 17,
                    'description_chars_per_line' => 36,
                    'header_image_web' => 'headers/Picture1.png',
                    'footer_image_web' => 'headers/Picture2.png',
                    'header_image_pdf' => 'headers/Picture1.png',
                    'footer_image_pdf' => 'headers/Picture2.png',
                ],
                'legal-portrait' => [
                    'pages_view' => 'gso::ptrs.print.paper.legal-portrait.pages',
                    'styles_view' => 'gso::ptrs.print.paper.legal-portrait.styles',
                    'pdf_styles_view' => 'gso::ptrs.print.paper.legal-portrait.pdf-styles',
                    'rows_per_page' => 26,
                    'grid_rows' => 14,
                    'last_page_grid_rows' => 26,
                    'description_chars_per_line' => 42,
                    'header_image_web' => 'headers/Picture1.png',
                    'footer_image_web' => 'headers/Picture2.png',
                    'header_image_pdf' => 'headers/Picture1.png',
                    'footer_image_pdf' => 'headers/Picture2.png',
                ],
            ],
        ],
        'gso_ics' => [
            'module' => 'GSO',
            'default_paper' => 'a4-portrait',
            'allowed_papers' => [
                'a4-portrait',
                'letter-portrait',
                'legal-portrait',
            ],
            'profiles' => [
                'a4-portrait' => [
                    'pages_view' => 'gso::ics.print.paper.a4-portrait.pages',
                    'styles_view' => 'gso::ics.print.paper.a4-portrait.styles',
                    'pdf_styles_view' => 'gso::ics.print.paper.a4-portrait.pdf-styles',
                    'rows_per_page' => 27,
                    'grid_rows' => 27,
                    'last_page_grid_rows' => 27,
                    'description_chars_per_line' => 42,
                    'item_column_widths' => [
                        'qty' => '5%',
                        'unit' => '6%',
                        'unit_cost' => '10%',
                        'total_cost' => '10%',
                        'description' => '39%',
                        'inventory_item_no' => '18%',
                        'useful_life' => '12%',
                    ],
                    'header_image_web' => 'headers/Picture1.png',
                    'footer_image_web' => 'headers/Picture2.png',
                    'header_image_pdf' => 'headers/Picture1.png',
                    'footer_image_pdf' => 'headers/Picture2.png',
                ],
                'letter-portrait' => [
                    'pages_view' => 'gso::ics.print.paper.letter-portrait.pages',
                    'styles_view' => 'gso::ics.print.paper.letter-portrait.styles',
                    'pdf_styles_view' => 'gso::ics.print.paper.letter-portrait.pdf-styles',
                    'rows_per_page' => 26,
                    'grid_rows' => 26,
                    'last_page_grid_rows' => 30,
                    'description_chars_per_line' => 40,
                    'header_image_web' => 'headers/Picture1.png',
                    'footer_image_web' => 'headers/Picture2.png',
                    'header_image_pdf' => 'headers/Picture1.png',
                    'footer_image_pdf' => 'headers/Picture2.png',
                ],
                'legal-portrait' => [
                    'pages_view' => 'gso::ics.print.paper.legal-portrait.pages',
                    'styles_view' => 'gso::ics.print.paper.legal-portrait.styles',
                    'pdf_styles_view' => 'gso::ics.print.paper.legal-portrait.pdf-styles',
                    'rows_per_page' => 34,
                    'grid_rows' => 34,
                    'last_page_grid_rows' => 40,
                    'description_chars_per_line' => 44,
                    'header_image_web' => 'headers/Picture1.png',
                    'footer_image_web' => 'headers/Picture2.png',
                    'header_image_pdf' => 'headers/Picture1.png',
                    'footer_image_pdf' => 'headers/Picture2.png',
                ],
            ],
        ],
        'gso_itr' => [
            'module' => 'GSO',
            'default_paper' => 'a4-portrait',
            'allowed_papers' => [
                'a4-portrait',
                'letter-portrait',
                'legal-portrait',
            ],
            'profiles' => [
                'a4-portrait' => [
                    'pages_view' => 'gso::itrs.print.paper.a4-portrait.pages',
                    'styles_view' => 'gso::itrs.print.paper.a4-portrait.styles',
                    'pdf_styles_view' => 'gso::itrs.print.paper.a4-portrait.pdf-styles',
                    'rows_per_page' => 12,
                    'grid_rows' => 12,
                    'last_page_grid_rows' => 12,
                    'description_chars_per_line' => 34,
                    'header_image_web' => 'headers/Picture1.png',
                    'footer_image_web' => 'headers/Picture2.png',
                    'header_image_pdf' => 'headers/Picture1.png',
                    'footer_image_pdf' => 'headers/Picture2.png',
                ],
                'letter-portrait' => [
                    'pages_view' => 'gso::itrs.print.paper.letter-portrait.pages',
                    'styles_view' => 'gso::itrs.print.paper.letter-portrait.styles',
                    'pdf_styles_view' => 'gso::itrs.print.paper.letter-portrait.pdf-styles',
                    'rows_per_page' => 11,
                    'grid_rows' => 11,
                    'last_page_grid_rows' => 11,
                    'description_chars_per_line' => 32,
                    'header_image_web' => 'headers/Picture1.png',
                    'footer_image_web' => 'headers/Picture2.png',
                    'header_image_pdf' => 'headers/Picture1.png',
                    'footer_image_pdf' => 'headers/Picture2.png',
                ],
                'legal-portrait' => [
                    'pages_view' => 'gso::itrs.print.paper.legal-portrait.pages',
                    'styles_view' => 'gso::itrs.print.paper.legal-portrait.styles',
                    'pdf_styles_view' => 'gso::itrs.print.paper.legal-portrait.pdf-styles',
                    'rows_per_page' => 14,
                    'grid_rows' => 14,
                    'last_page_grid_rows' => 14,
                    'description_chars_per_line' => 36,
                    'header_image_web' => 'headers/Picture1.png',
                    'footer_image_web' => 'headers/Picture2.png',
                    'header_image_pdf' => 'headers/Picture1.png',
                    'footer_image_pdf' => 'headers/Picture2.png',
                ],
            ],
        ],
        'gso_wmr' => [
            'module' => 'GSO',
            'default_paper' => 'a4-portrait',
            'allowed_papers' => [
                'a4-portrait',
                'letter-portrait',
                'legal-portrait',
            ],
            'profiles' => [
                'a4-portrait' => [
                    'pages_view' => 'gso::wmrs.print.paper.a4-portrait.pages',
                    'styles_view' => 'gso::wmrs.print.paper.a4-portrait.styles',
                    'pdf_styles_view' => 'gso::wmrs.print.paper.a4-portrait.pdf-styles',
                    'rows_per_page' => 16,
                    'grid_rows' => 10,
                    'last_page_grid_rows' => 16,
                    'description_chars_per_line' => 34,
                    'header_image_web' => 'headers/Picture1.png',
                    'footer_image_web' => 'headers/Picture2.png',
                    'header_image_pdf' => 'headers/Picture1.png',
                    'footer_image_pdf' => 'headers/Picture2.png',
                ],
                'letter-portrait' => [
                    'pages_view' => 'gso::wmrs.print.paper.letter-portrait.pages',
                    'styles_view' => 'gso::wmrs.print.paper.letter-portrait.styles',
                    'pdf_styles_view' => 'gso::wmrs.print.paper.letter-portrait.pdf-styles',
                    'rows_per_page' => 13,
                    'grid_rows' => 10,
                    'last_page_grid_rows' => 13,
                    'description_chars_per_line' => 36,
                    'header_image_web' => 'headers/Picture1.png',
                    'footer_image_web' => 'headers/Picture2.png',
                    'header_image_pdf' => 'headers/Picture1.png',
                    'footer_image_pdf' => 'headers/Picture2.png',
                ],
                'legal-portrait' => [
                    'pages_view' => 'gso::wmrs.print.paper.legal-portrait.pages',
                    'styles_view' => 'gso::wmrs.print.paper.legal-portrait.styles',
                    'pdf_styles_view' => 'gso::wmrs.print.paper.legal-portrait.pdf-styles',
                    'rows_per_page' => 22,
                    'grid_rows' => 12,
                    'last_page_grid_rows' => 22,
                    'description_chars_per_line' => 40,
                    'header_image_web' => 'headers/Picture1.png',
                    'footer_image_web' => 'headers/Picture2.png',
                    'header_image_pdf' => 'headers/Picture1.png',
                    'footer_image_pdf' => 'headers/Picture2.png',
                ],
            ],
        ],
    ],
];

foreach ($config['printables'] as &$printable) {
    foreach (($printable['profiles'] ?? []) as &$profile) {
        $profile['pdf_preview_fragment'] = $profile['pdf_preview_fragment']
            ?? 'toolbar=0&navpanes=0&scrollbar=0&zoom=100';
    }
}

unset($printable, $profile);

return $config;
