<?php

return [
    'printables' => [
        'gso_air' => [
            'module' => 'GSO',
            'default_paper' => 'a4-portrait',
            'allowed_papers' => [
                'a4-portrait',
                'letter-portrait',
                'legal-portrait',
            ],
            'profiles' => [
                'a4-portrait' => [
                    'pages_view' => 'gso::air.print.paper.a4-portrait.pages',
                    'styles_view' => 'gso::air.print.paper.a4-portrait.styles',
                    'pdf_styles_view' => 'gso::air.print.paper.a4-portrait.pdf-styles',
                    'rows_per_page' => 31,
                    'grid_rows' => 31,
                    'last_page_grid_rows' => 24,
                    'description_chars_per_line' => 73,
                    'header_image_web' => 'headers/Picture1.png',
                    'footer_image_web' => 'headers/Picture2.png',
                ],
                'letter-portrait' => [
                    'pages_view' => 'gso::air.print.paper.letter-portrait.pages',
                    'styles_view' => 'gso::air.print.paper.letter-portrait.styles',
                    'pdf_styles_view' => 'gso::air.print.paper.letter-portrait.pdf-styles',
                    'rows_per_page' => 52,
                    'grid_rows' => 51,
                    'last_page_grid_rows' => 34,
                    'description_chars_per_line' => 40,
                ],
                'legal-portrait' => [
                    'pages_view' => 'gso::air.print.paper.legal-portrait.pages',
                    'styles_view' => 'gso::air.print.paper.legal-portrait.styles',
                    'pdf_styles_view' => 'gso::air.print.paper.legal-portrait.pdf-styles',
                    'rows_per_page' => 63,
                    'grid_rows' => 60,
                    'last_page_grid_rows' => 33,
                    'description_chars_per_line' => 72,
                ],
            ],
        ],
        'gso_ris' => [
            'module' => 'GSO',
            'default_paper' => 'a4-portrait',
            'allowed_papers' => [
                'a4-portrait',
                'letter-portrait',
                'legal-portrait',
            ],
            'profiles' => [
                'a4-portrait' => [
                    'pages_view' => 'gso::ris.print.paper.a4-portrait.pages',
                    'styles_view' => 'gso::ris.print.paper.a4-portrait.styles',
                    'pdf_styles_view' => 'gso::ris.print.paper.a4-portrait.pdf-styles',
                    'rows_per_page' => 74,
                    'grid_rows' => 72,
                    'last_page_grid_rows' => 31,
                    'description_chars_per_line' => 40,
                ],
                'letter-portrait' => [
                    'pages_view' => 'gso::ris.print.paper.letter-portrait.pages',
                    'styles_view' => 'gso::ris.print.paper.letter-portrait.styles',
                    'pdf_styles_view' => 'gso::ris.print.paper.letter-portrait.pdf-styles',
                    'rows_per_page' => 68,
                    'grid_rows' => 68,
                    'last_page_grid_rows' => 29,
                    'description_chars_per_line' => 40,
                ],
                'legal-portrait' => [
                    'pages_view' => 'gso::ris.print.paper.legal-portrait.pages',
                    'styles_view' => 'gso::ris.print.paper.legal-portrait.styles',
                    'pdf_styles_view' => 'gso::ris.print.paper.legal-portrait.pdf-styles',
                    'rows_per_page' => 76,
                    'grid_rows' => 76,
                    'last_page_grid_rows' => 37,
                    'description_chars_per_line' => 40,
                ],
            ],
        ],
        'gso_par' => [
            'module' => 'GSO',
            'default_paper' => 'a4-portrait',
            'allowed_papers' => [
                'a4-portrait',
                'letter-portrait',
                'legal-portrait',
            ],
            'profiles' => [
                'a4-portrait' => [
                    'pages_view' => 'gso::pars.print.paper.a4-portrait.pages',
                    'styles_view' => 'gso::pars.print.paper.a4-portrait.styles',
                    'pdf_styles_view' => 'gso::pars.print.paper.a4-portrait.pdf-styles',
                    'rows_per_page' => 29,
                    'grid_rows' => 30,
                    'last_page_grid_rows' => 33,
                    'description_chars_per_line' => 40,
                    'header_image_web' => 'headers/Picture1.png',
                    'footer_image_web' => 'headers/Picture2.png',
                ],
                'letter-portrait' => [
                    'pages_view' => 'gso::pars.print.paper.letter-portrait.pages',
                    'styles_view' => 'gso::pars.print.paper.letter-portrait.styles',
                    'pdf_styles_view' => 'gso::pars.print.paper.letter-portrait.pdf-styles',
                    'rows_per_page' => 24,
                    'grid_rows' => 24,
                    'last_page_grid_rows' => 29,
                    'description_chars_per_line' => 38,
                    'header_image_web' => 'headers/Picture1.png',
                    'footer_image_web' => 'headers/Picture2.png',
                ],
                'legal-portrait' => [
                    'pages_view' => 'gso::pars.print.paper.legal-portrait.pages',
                    'styles_view' => 'gso::pars.print.paper.legal-portrait.styles',
                    'pdf_styles_view' => 'gso::pars.print.paper.legal-portrait.pdf-styles',
                    'rows_per_page' => 30,
                    'grid_rows' => 30,
                    'last_page_grid_rows' => 39,
                    'description_chars_per_line' => 42,
                    'header_image_web' => 'headers/Picture1.png',
                    'footer_image_web' => 'headers/Picture2.png',
                ],
            ],
        ],
        'gso_ptr' => [
            'module' => 'GSO',
            'default_paper' => 'a4-portrait',
            'allowed_papers' => [
                'a4-portrait',
                'letter-portrait',
                'legal-portrait',
            ],
            'profiles' => [
                'a4-portrait' => [
                    'pages_view' => 'gso::ptrs.print.paper.a4-portrait.pages',
                    'styles_view' => 'gso::ptrs.print.paper.a4-portrait.styles',
                    'pdf_styles_view' => 'gso::ptrs.print.paper.a4-portrait.pdf-styles',
                    'rows_per_page' => 20,
                    'grid_rows' => 12,
                    'last_page_grid_rows' => 20,
                    'description_chars_per_line' => 38,
                    'header_image_web' => 'headers/Picture1.png',
                    'footer_image_web' => 'headers/Picture2.png',
                    'header_image_pdf' => 'headers/Picture1.png',
                    'footer_image_pdf' => 'headers/Picture2.png',
                ],
                'letter-portrait' => [
                    'pages_view' => 'gso::ptrs.print.paper.letter-portrait.pages',
                    'styles_view' => 'gso::ptrs.print.paper.letter-portrait.styles',
                    'pdf_styles_view' => 'gso::ptrs.print.paper.letter-portrait.pdf-styles',
                    'rows_per_page' => 17,
                    'grid_rows' => 11,
                    'last_page_grid_rows' => 17,
                    'description_chars_per_line' => 36,
                    'header_image_web' => 'headers/Picture1.png',
                    'footer_image_web' => 'headers/Picture2.png',
                    'header_image_pdf' => 'headers/Picture1.png',
                    'footer_image_pdf' => 'headers/Picture2.png',
                ],
                'legal-portrait' => [
                    'pages_view' => 'gso::ptrs.print.paper.legal-portrait.pages',
                    'styles_view' => 'gso::ptrs.print.paper.legal-portrait.styles',
                    'pdf_styles_view' => 'gso::ptrs.print.paper.legal-portrait.pdf-styles',
                    'rows_per_page' => 26,
                    'grid_rows' => 14,
                    'last_page_grid_rows' => 26,
                    'description_chars_per_line' => 42,
                    'header_image_web' => 'headers/Picture1.png',
                    'footer_image_web' => 'headers/Picture2.png',
                    'header_image_pdf' => 'headers/Picture1.png',
                    'footer_image_pdf' => 'headers/Picture2.png',
                ],
            ],
        ],
        'gso_ics' => [
            'module' => 'GSO',
            'default_paper' => 'a4-portrait',
            'allowed_papers' => [
                'a4-portrait',
                'letter-portrait',
                'legal-portrait',
            ],
            'profiles' => [
                'a4-portrait' => [
                    'pages_view' => 'gso::ics.print.paper.a4-portrait.pages',
                    'styles_view' => 'gso::ics.print.paper.a4-portrait.styles',
                    'pdf_styles_view' => 'gso::ics.print.paper.a4-portrait.pdf-styles',
                    'rows_per_page' => 28,
                    'grid_rows' => 28,
                    'last_page_grid_rows' => 33,
                    'description_chars_per_line' => 42,
                    'header_image_web' => 'headers/Picture1.png',
                    'footer_image_web' => 'headers/Picture2.png',
                    'header_image_pdf' => 'headers/Picture1.png',
                    'footer_image_pdf' => 'headers/Picture2.png',
                ],
                'letter-portrait' => [
                    'pages_view' => 'gso::ics.print.paper.letter-portrait.pages',
                    'styles_view' => 'gso::ics.print.paper.letter-portrait.styles',
                    'pdf_styles_view' => 'gso::ics.print.paper.letter-portrait.pdf-styles',
                    'rows_per_page' => 26,
                    'grid_rows' => 26,
                    'last_page_grid_rows' => 30,
                    'description_chars_per_line' => 40,
                    'header_image_web' => 'headers/Picture1.png',
                    'footer_image_web' => 'headers/Picture2.png',
                    'header_image_pdf' => 'headers/Picture1.png',
                    'footer_image_pdf' => 'headers/Picture2.png',
                ],
                'legal-portrait' => [
                    'pages_view' => 'gso::ics.print.paper.legal-portrait.pages',
                    'styles_view' => 'gso::ics.print.paper.legal-portrait.styles',
                    'pdf_styles_view' => 'gso::ics.print.paper.legal-portrait.pdf-styles',
                    'rows_per_page' => 34,
                    'grid_rows' => 34,
                    'last_page_grid_rows' => 40,
                    'description_chars_per_line' => 44,
                    'header_image_web' => 'headers/Picture1.png',
                    'footer_image_web' => 'headers/Picture2.png',
                    'header_image_pdf' => 'headers/Picture1.png',
                    'footer_image_pdf' => 'headers/Picture2.png',
                ],
            ],
        ],
        'gso_itr' => [
            'module' => 'GSO',
            'default_paper' => 'a4-portrait',
            'allowed_papers' => [
                'a4-portrait',
                'letter-portrait',
                'legal-portrait',
            ],
            'profiles' => [
                'a4-portrait' => [
                    'pages_view' => 'gso::itrs.print.paper.a4-portrait.pages',
                    'styles_view' => 'gso::itrs.print.paper.a4-portrait.styles',
                    'pdf_styles_view' => 'gso::itrs.print.paper.a4-portrait.pdf-styles',
                    'rows_per_page' => 12,
                    'grid_rows' => 12,
                    'last_page_grid_rows' => 12,
                    'description_chars_per_line' => 34,
                    'header_image_web' => 'headers/Picture1.png',
                    'footer_image_web' => 'headers/Picture2.png',
                    'header_image_pdf' => 'headers/Picture1.png',
                    'footer_image_pdf' => 'headers/Picture2.png',
                ],
                'letter-portrait' => [
                    'pages_view' => 'gso::itrs.print.paper.letter-portrait.pages',
                    'styles_view' => 'gso::itrs.print.paper.letter-portrait.styles',
                    'pdf_styles_view' => 'gso::itrs.print.paper.letter-portrait.pdf-styles',
                    'rows_per_page' => 11,
                    'grid_rows' => 11,
                    'last_page_grid_rows' => 11,
                    'description_chars_per_line' => 32,
                    'header_image_web' => 'headers/Picture1.png',
                    'footer_image_web' => 'headers/Picture2.png',
                    'header_image_pdf' => 'headers/Picture1.png',
                    'footer_image_pdf' => 'headers/Picture2.png',
                ],
                'legal-portrait' => [
                    'pages_view' => 'gso::itrs.print.paper.legal-portrait.pages',
                    'styles_view' => 'gso::itrs.print.paper.legal-portrait.styles',
                    'pdf_styles_view' => 'gso::itrs.print.paper.legal-portrait.pdf-styles',
                    'rows_per_page' => 14,
                    'grid_rows' => 14,
                    'last_page_grid_rows' => 14,
                    'description_chars_per_line' => 36,
                    'header_image_web' => 'headers/Picture1.png',
                    'footer_image_web' => 'headers/Picture2.png',
                    'header_image_pdf' => 'headers/Picture1.png',
                    'footer_image_pdf' => 'headers/Picture2.png',
                ],
            ],
        ],
        'gso_wmr' => [
            'module' => 'GSO',
            'default_paper' => 'a4-portrait',
            'allowed_papers' => [
                'a4-portrait',
                'letter-portrait',
                'legal-portrait',
            ],
            'profiles' => [
                'a4-portrait' => [
                    'pages_view' => 'gso::wmrs.print.paper.a4-portrait.pages',
                    'styles_view' => 'gso::wmrs.print.paper.a4-portrait.styles',
                    'pdf_styles_view' => 'gso::wmrs.print.paper.a4-portrait.pdf-styles',
                    'rows_per_page' => 10,
                    'grid_rows' => 10,
                    'last_page_grid_rows' => 10,
                    'description_chars_per_line' => 34,
                    'header_image_web' => 'headers/Picture1.png',
                    'footer_image_web' => 'headers/Picture2.png',
                    'header_image_pdf' => 'headers/Picture1.png',
                    'footer_image_pdf' => 'headers/Picture2.png',
                ],
                'letter-portrait' => [
                    'pages_view' => 'gso::wmrs.print.paper.letter-portrait.pages',
                    'styles_view' => 'gso::wmrs.print.paper.letter-portrait.styles',
                    'pdf_styles_view' => 'gso::wmrs.print.paper.letter-portrait.pdf-styles',
                    'rows_per_page' => 10,
                    'grid_rows' => 10,
                    'last_page_grid_rows' => 10,
                    'description_chars_per_line' => 36,
                    'header_image_web' => 'headers/Picture1.png',
                    'footer_image_web' => 'headers/Picture2.png',
                    'header_image_pdf' => 'headers/Picture1.png',
                    'footer_image_pdf' => 'headers/Picture2.png',
                ],
                'legal-portrait' => [
                    'pages_view' => 'gso::wmrs.print.paper.legal-portrait.pages',
                    'styles_view' => 'gso::wmrs.print.paper.legal-portrait.styles',
                    'pdf_styles_view' => 'gso::wmrs.print.paper.legal-portrait.pdf-styles',
                    'rows_per_page' => 12,
                    'grid_rows' => 12,
                    'last_page_grid_rows' => 12,
                    'description_chars_per_line' => 40,
                    'header_image_web' => 'headers/Picture1.png',
                    'footer_image_web' => 'headers/Picture2.png',
                    'header_image_pdf' => 'headers/Picture1.png',
                    'footer_image_pdf' => 'headers/Picture2.png',
                ],
            ],
        ],
    ],
];
