<?php

namespace App\Repositories\Eloquent;

use App\Models\Permission;
use App\Repositories\Contracts\PermissionRepositoryInterface;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;

class EloquentPermissionRepository implements PermissionRepositoryInterface
{
    public function paginate(int $perPage = 30): LengthAwarePaginator
    {
        return Permission::query()
            ->orderBy('page')
            ->orderBy('name')
            ->paginate($perPage);
    }

    public function create(array $attributes): Permission
    {
        // UUID is auto-generated by your Permission model's boot()
        return Permission::create($attributes);
    }

    public function delete(Permission $permission): void
    {
        $permission->delete();
    }
}
